# LINEAR REGRESSION

Linear regression with mutiple variables

Dependent variable: y

independent variables: x1, x2, ..., xn

y = m1*x1 + m2*x2 + ... + mn*xn + b

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms.median()

np.float64(4.0)

In [5]:
# missing data point in bedrooms
# filling it with median
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median()) #fillna is used to fill missing values
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)
print("Coefficients:", reg.coef_)
print("Intercept:", reg.intercept_)

Coefficients: [  112.06244194 23388.88007794 -3231.71790863]
Intercept: 221323.0018654043


In [7]:
reg.predict([[3000, 3, 40]])

e:\Summer_2025\ML_Py\ml_env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [45]:
#exercise 
df2 = pd.read_csv('hiring.csv')
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [46]:

df2.experience = df2.experience.fillna('zero')
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [47]:
def convert_experience(exp):
    word_to_num_map = {
        'zero': 0,
        'one': 1,
        'two': 2,
        'three': 3,
        'four': 4,
        'five': 5,
        'six': 6,
        'seven': 7,
        'eight': 8,
        'nine': 9,
        'ten': 10,
        'eleven': 11,
        'twelve': 12
    }
    return word_to_num_map.get(exp, 0)

df2['experience'] = df2['experience'].apply(convert_experience)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [48]:
import math
median_test_score = math.floor(df2['test_score(out of 10)'].mean())
median_test_score

7

In [49]:
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(median_test_score)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [52]:
linreg_2 = linear_model.LinearRegression()
linreg_2.fit(df2[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df2['salary($)'])
print("Coefficients:", linreg_2.coef_)
print("Intercept:", linreg_2.intercept_)

Coefficients: [2922.26901502 2221.30909959 2147.48256637]
Intercept: 14992.65144669314


In [53]:
reg.predict([[2,9,6]])

e:\Summer_2025\ML_Py\ml_env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([412656.73999894])

In [54]:
reg.predict([[12,10,10]])

e:\Summer_2025\ML_Py\ml_env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([424239.37286177])